-- MySQL Script generated by MySQL Workbench
-- seg 02 set 2019 23:04:43 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sgco
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sgco` ;

-- -----------------------------------------------------
-- Schema sgco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgco` DEFAULT CHARACTER SET utf8 ;
USE `sgco` ;

-- -----------------------------------------------------
-- Table `sgco`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgco`.`usuario` ;

CREATE TABLE IF NOT EXISTS `sgco`.`usuario` (
  `id` INT NOT NULL,
  `login` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `imagem` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgco`.`pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgco`.`pais` ;

CREATE TABLE IF NOT EXISTS `sgco`.`pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `sigla` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgco`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgco`.`estado` ;

CREATE TABLE IF NOT EXISTS `sgco`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(75) NOT NULL,
  `uf` VARCHAR(5) NOT NULL,
  `id_pais` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estado_pais_idx` (`id_pais` ASC),
  CONSTRAINT `fk_estado_pais`
    FOREIGN KEY (`id_pais`)
    REFERENCES `sgco`.`pais` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgco`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgco`.`cidade` ;

CREATE TABLE IF NOT EXISTS `sgco`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `id_estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidade_estado1_idx` (`id_estado` ASC),
  CONSTRAINT `fk_cidade_estado`
    FOREIGN KEY (`id_estado`)
    REFERENCES `sgco`.`estado` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 5565
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgco`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgco`.`endereco` ;

CREATE TABLE IF NOT EXISTS `sgco`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(60) NOT NULL,
  `bairro` VARCHAR(60) NULL,
  `numero` VARCHAR(10) NULL,
  `cep` VARCHAR(10) NULL,
  `complemento` VARCHAR(60) NULL,
  `id_cidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_endereco_cidade_idx` (`id_cidade` ASC),
  CONSTRAINT `fk_endereco_cidade`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `sgco`.`cidade` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgco`.`contato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgco`.`contato` ;

CREATE TABLE IF NOT EXISTS `sgco`.`contato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NULL,
  `telefone1` VARCHAR(20) NOT NULL,
  `telefone2` VARCHAR(20) NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgco`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgco`.`funcionario` ;

CREATE TABLE IF NOT EXISTS `sgco`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `rg` VARCHAR(12) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `nascimento` DATE NOT NULL,
  `cor_agenda` VARCHAR(10) NOT NULL,
  `crm_cro` VARCHAR(45) NULL,
  `ativo` TINYINT(1) NOT NULL,
  `cod_tipo` INT NOT NULL,
  `id_endereco` INT NOT NULL,
  `id_contato` INT NOT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `cod_tipo_ENUM` (`cod_tipo` ASC),
  INDEX `fk_funcionario_endereco_idx` (`id_endereco` ASC),
  INDEX `fk_funcionario_contato_idx` (`id_contato` ASC),
  UNIQUE INDEX `id_endereco_UNIQUE` (`id_endereco` ASC),
  UNIQUE INDEX `id_contato_UNIQUE` (`id_contato` ASC),
  INDEX `fk_funcionario_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_funcionario_endereco`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `sgco`.`endereco` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_funcionario_contato`
    FOREIGN KEY (`id_contato`)
    REFERENCES `sgco`.`contato` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_funcionario_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sgco`.`usuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgco`.`paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgco`.`paciente` ;

CREATE TABLE IF NOT EXISTS `sgco`.`paciente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `cpf` VARCHAR(14) NULL,
  `sexo` VARCHAR(1) NULL,
  `nascimento` DATE NULL,
  `odontograma` JSON NOT NULL,
  `id_contato` INT NOT NULL,
  `id_endereco` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_paciente_contato_idx` (`id_contato` ASC),
  UNIQUE INDEX `id_contato_UNIQUE` (`id_contato` ASC),
  INDEX `fk_paciente_endereco_idx` (`id_endereco` ASC),
  UNIQUE INDEX `id_endereco_UNIQUE` (`id_endereco` ASC),
  CONSTRAINT `fk_paciente_contato`
    FOREIGN KEY (`id_contato`)
    REFERENCES `sgco`.`contato` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_paciente_endereco`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `sgco`.`endereco` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgco`.`permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgco`.`permissao` ;

CREATE TABLE IF NOT EXISTS `sgco`.`permissao` (
  `id_usuario` INT NOT NULL,
  `cod_permissao` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `cod_permissao`),
  INDEX `fk_permissoes_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_permissoes_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sgco`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgco`.`anotacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgco`.`anotacao` ;

CREATE TABLE IF NOT EXISTS `sgco`.`anotacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `conteudo` MEDIUMTEXT NOT NULL,
  `id_paciente` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_anotacao_paciente_idx` (`id_paciente` ASC),
  CONSTRAINT `fk_anotacao_paciente`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `sgco`.`paciente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgco`.`procedimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgco`.`procedimento` ;

CREATE TABLE IF NOT EXISTS `sgco`.`procedimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgco`.`agendamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgco`.`agendamento` ;

CREATE TABLE IF NOT EXISTS `sgco`.`agendamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `anamnese` MEDIUMTEXT NULL,
  `diagnostico` MEDIUMTEXT NULL,
  `receituario` JSON NULL,
  `atestado` JSON NULL,
  `data_hora_inicio` DATETIME NOT NULL,
  `data_hora_fim` DATETIME NOT NULL,
  `observacao` MEDIUMTEXT NULL,
  `cod_status` INT NOT NULL,
  `id_paciente` INT NOT NULL,
  `id_funcionario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agendamento_paciente_idx` (`id_paciente` ASC),
  INDEX `fk_agendamento_funcionario_idx` (`id_funcionario` ASC),
  CONSTRAINT `fk_agendamento_paciente`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `sgco`.`paciente` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_agendamento_funcionario`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `sgco`.`funcionario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgco`.`procedimento_agendado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgco`.`procedimento_agendado` ;

CREATE TABLE IF NOT EXISTS `sgco`.`procedimento_agendado` (
  `id_procedimento` INT NOT NULL,
  `id_agendamento` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `desconto` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id_procedimento`, `id_agendamento`),
  INDEX `fk_procedimento_agendado_agendamento_idx` (`id_agendamento` ASC),
  INDEX `fk_procedimento_agendado_procedimento_idx` (`id_procedimento` ASC),
  CONSTRAINT `fk_procedimento_agendado_procedimento`
    FOREIGN KEY (`id_procedimento`)
    REFERENCES `sgco`.`procedimento` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_procedimento_agendado_agendamento`
    FOREIGN KEY (`id_agendamento`)
    REFERENCES `sgco`.`agendamento` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgco`.`conta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgco`.`conta` ;

CREATE TABLE IF NOT EXISTS `sgco`.`conta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cod_tipo` INT NOT NULL,
  `ativa` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  INDEX `cod_tipo_ENUM` (`cod_tipo` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgco`.`movimentacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgco`.`movimentacao` ;

CREATE TABLE IF NOT EXISTS `sgco`.`movimentacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  `cod_tipo` INT NOT NULL,
  `cod_status` INT NOT NULL,
  `id_conta` INT NOT NULL,
  `id_agendamento` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `cod_tipo_ENUM` (`cod_tipo` ASC),
  INDEX `fk_movimentacao_conta_idx` (`id_conta` ASC),
  INDEX `fk_movimentacao_agendamento_idx` (`id_agendamento` ASC),
  CONSTRAINT `fk_movimentacao_conta`
    FOREIGN KEY (`id_conta`)
    REFERENCES `sgco`.`conta` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_movimentacao_agendamento`
    FOREIGN KEY (`id_agendamento`)
    REFERENCES `sgco`.`agendamento` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgco`.`parcela`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgco`.`parcela` ;

CREATE TABLE IF NOT EXISTS `sgco`.`parcela` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vencimento` DATE NOT NULL,
  `data` DATE NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `cod_status` INT NOT NULL,
  `id_movimentacao` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_parcela_movimentacao_idx` (`id_movimentacao` ASC),
  CONSTRAINT `fk_parcela_movimentacao`
    FOREIGN KEY (`id_movimentacao`)
    REFERENCES `sgco`.`movimentacao` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
